x = float(input("Enter a number: "))
y = float(input("Enter another number: "))
print("Addition : ",(x + y))       
print("Subtraction : ",(x - y))
print("Multiplication : ",(x * y))
print("Division : ",(x / y))